Repository wecode-bootcamp-korea/30-1st-WoowaSiblings-backend, pull requests merged in 2022-03, with the labels that each got.

#1 [30기 김은지] modeling
  core/__init__.py
  core/admin.py
  core/apps.py
  core/migrations/__init__.py
  core/models.py
  core/tests.py
  core/views.py
  orders/__init__.py
  orders/admin.py
  orders/apps.py
  orders/migrations/__init__.py
  orders/models.py
  orders/tests.py
  orders/views.py
  products/__init__.py
  products/admin.py
  products/apps.py
  products/migrations/__init__.py
  products/models.py
  products/tests.py
  products/views.py
  reviews/__init__.py
  reviews/admin.py
  reviews/apps.py
  reviews/migrations/__init__.py
  reviews/models.py
  reviews/tests.py
  reviews/views.py
  users/__init__.py
  users/admin.py
  users/apps.py
  users/migrations/__init__.py
  users/models.py
  users/tests.py
  users/views.py
Labels: Status: 수정 요청

#4 Modify : models.py
  .gitignore
  orders/models.py
  products/models.py
Labels: Status: Accepted

#2 Add : views.py
  .gitignore
  moonbanggu/settings.py
  moonbanggu/urls.py
  orders/models.py
  products/models.py
  users/models.py
  users/urls.py
  users/views.py
  utils/decorators.py
Labels: Status: 수정 요청

#5 [김동규] 전체 페이지, 카테고리 페이지 기능 구현
  moonbanggu/urls.py
  orders/migrations/0001_initial.py
  products/migrations/0001_initial.py
  products/urls.py
  products/views.py
  reviews/migrations/0001_initial.py
  users/migrations/0001_initial.py
Labels: Status: 리뷰 요청

#6 [김은지] 상품 상세페이지 구현
  products/urls.py
  products/views.py
Labels: Status: Accepted

#10 [김은지] oders/models.py 수정
  orders/migrations/0002_alter_cart_product_time_alter_orderitem_product_time.py
  orders/models.py
Labels: Status: 리뷰 요청

#7 [김은지] 좋아요 기능 구현
  moonbanggu/urls.py
  products/urls.py
  products/views.py
Labels: Status: 리뷰 요청

#12 [김동규] products app views.py 수정
  products/views.py
Labels: Status: 리뷰 요청

#11 [김동규] 장바구니 CRUD 기능 구현
  moonbanggu/urls.py
  orders/urls.py
  orders/views.py
  products/urls.py
  products/views.py
  utils/decorators.py
Labels: Status: 수정 요청
